# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    allowUnstable: true
    addToPath: true
    architecture: 'x64'
- script: pip3 freeze > requirements.txt
  displayName: 'pip install notebook reqs'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'set up sdk'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'Project1SCN'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      sed -i -e "s/<afdebeae-4fec-483a-bb31-a0bef27f4c72>/$(afdebeae-4fec-483a-bb31-a0bef27f4c72)/g" sklearn-diabetes.ipynb
                 sed -i -e "s/<HANU-ROHIT-RG>/$(HANU-ROHIT-RG)/g" sklearn-diabetes.ipynb
                 sed -i -e "s/<Dbricks-hanu>/$(Dbricks-hanu)/g" sklearn-diabetes.ipynb
                 sed -i -e "s/DefaultAzureCredential/AzureCliCredential/g" sklearn-diabetes.ipynb
                 papermill -k python sklearn-diabetes.ipynb sklearn-diabetes.output.ipynb
          workingDirectory: 'sdk/python/jobs/single-step/scikit-learn/diabetes'